### ISSUE TITLE
Glyph for T-cedilla is the same as the one for T-comma

### ISSUE THREAD

**Issue by fitojb** [googlefonts/roboto-serif#12]
T-cedilla (Ţţ) is used in the Gagauz language. Compare with ⟨Țț⟩, used in Romanian.

![image](https://user-images.githubusercontent.com/554953/154881996-f8462c3b-f489-47e4-97c5-c3eee6b44724.png)

**Comment by danburzo** [comment]
As of Version 1.007, T-Comma seems to be missing altogether from Roboto Serif Variable. The glyph is mapped strictly to the T-Cedilla codepoint. This makes it currently cumbersome to typeset Romanian text.

**Comment by danburzo** [comment]
Awesome news, @m4rc1e! Will there be a v1.008 release soon?

**Comment by m4rc1e** [comment]
Just pushed it, https://github.com/googlefonts/roboto-serif/releases/tag/v1.008. Thank you for your patience and sorry it took so long.

**Comment by danburzo** [comment]
Thanks @m4rc1e, I confirm Roboto Serif is now Romanian-ready!
