### ISSUE TITLE
Add Cyrillic glyphs

### ISSUE THREAD

**Issue by Twilightssuperb** [googlefonts/roboto-serif#16]
Just type here that there's no Cyrillic languages support at font now.

**Comment by mrecord** [comment]
Correct. The fonts do not support the Cyrillic languages at this time.

**Comment by Twilightssuperb** [comment]
But I just ask for Cyrlllic implementation and some details for it — is it possible and how long it takes to make these changes...

**Comment by davelab6** [comment]
@Twilightssuperb thanks for reaching out. The Google Fonts team is aware of the need for Cyrillic and Greek support to enable Eurasian use.

**Comment by fitojb** [comment]
#20 fixes this
